import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Dimensions,
} from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';

const { width } = Dimensions.get('window');
const isMobile = width < 768;

const COLORS = {
  primary: '#2563EB',
  white: '#FFFFFF',
  lightGray: '#F8F9FA',
  gray: '#6B7280',
  darkGray: '#374151',
  textDark: '#1F2937',
  border: '#E5E7EB',
  background: '#F0F4F8',
};

export default function MerchantAgreementScreen() {
  const router = useRouter();

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity 
          style={styles.backButton}
          onPress={() => router.back()}
        >
          <Ionicons name="arrow-back" size={24} color={COLORS.darkGray} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Merchant Agreement</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.card}>
          <Text style={styles.mainTitle}>MERCHANT AGREEMENT</Text>
          <Text style={styles.version}>Version 1.0</Text>

          <Text style={styles.paragraph}>
            This Merchant Agreement ("Agreement") is between you (company/individual/firm/partnership/body corporate), together with any company or other business entity you are representing, if any (hereinafter collectively referred as "Merchant" or "you" or "User"); and Shipreward Logistics Private Limited, a company incorporated under the laws of India, having its registered office at 477, AR Mall, Near Vip Circle, Mota Varachha, Surat, Gujarat 394101 offering 'Logistics Management Services', under the name 'Shipreward' (hereinafter referred to as "we" or "Shipreward" or "Company", and together with the User referred jointly as the "Parties" and individually as a "Party").
          </Text>

          <Text style={styles.sectionTitle}>BACKGROUND</Text>
          <Text style={styles.paragraph}>
            This Agreement comes into effect when you register to use the Services (as defined below), or click on "Continue" box, and accept the terms and conditions provided herein.
          </Text>
          <Text style={styles.paragraph}>
            By registering or clicking on the 'Continue' box, you signify your absolute, irrevocable and unconditional consent to all the provisions of this Agreement in its entirety. This Agreement constitutes a legally binding agreement between you and Shipreward. This Agreement is an extension of the terms and conditions which can be viewed below in (Annexure 1) and privacy policy (Annexure 2), under which you're allowed to use Shipreward's website ("Website") and application ("App"), and how Shipreward will treat your account while you are a member. If you have any questions about our terms, feel free to contact us at support@shipreward.in.
          </Text>
          <Text style={styles.paragraph}>
            You are advised to read this Agreement carefully. You expressly represent and warrant that you will not avail the Services if you do not understand, agree to become a party to, and abide by all of the terms and conditions specified below. Any violation of this Agreement may result in legal liability upon you.
          </Text>
          <Text style={styles.paragraph}>
            The Website/App and the online/offline services of Shipreward or its affiliates, provides access to a platform that facilitates more comfortable form of e-commerce where you can use the logistics services according to your requirements as designated by Shipreward from time to time ("Service(s)").
          </Text>
          <Text style={styles.paragraph}>
            This Agreement is an electronic record in terms of Information Technology Act, 2000 and generated by a computer system, and does not require any physical or digital signatures. This Agreement is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011.
          </Text>
          <Text style={styles.paragraph}>
            Shipreward reserves the right to modify the terms of this Agreement, at any time, without giving you any prior notice. Your use of the Service following any such modification constitutes your agreement to follow and be bound by the terms of the Agreement, as modified.
          </Text>

          <Text style={styles.sectionTitle}>I. DEFINITIONS</Text>
          <Text style={styles.paragraph}>
            All capitalized terms used in this Merchant Agreement shall have the meanings ascribed to them in the Terms & Conditions and Privacy Policy, unless the context otherwise provides or requires.
          </Text>

          <Text style={styles.sectionTitle}>II. METHODOLOGY FOR PRICING</Text>
          <Text style={styles.paragraph}>
            With respect to Shipments, we have specific weight and size limitations for each individual Shipment which may vary basis the Shipping Vendor and/or location to which the Shipment is being shipped, although there is no restriction to the total weight of all Your Shipments collectively or on the number of boxes in each of Your Shipment.
          </Text>
          <Text style={styles.paragraph}>
            Volumetric weight of a Shipment will be system calculated at the time of booking in the panel of the Platforms. The formula used to calculate the volumetric weight is:
          </Text>
          <Text style={styles.formula}>length(cm) x breadth(cm) x height(cm) / 5000</Text>
          <Text style={styles.paragraph}>
            For example, if a shipment has the following dimensions:{'\n'}
            Length 30cm, Breadth 25cm, Height 40cm{'\n'}
            The volumetric weight will be: 30 x 25 x 40 / 5000 = 6 KGs
          </Text>
          <Text style={styles.paragraph}>
            For all shipments, billing will be based on the following criteria:
          </Text>
          <Text style={styles.bulletPoint}>• For shipments with a volumetric weight up to 5kg, charges will be applied on the basis of dead weight.</Text>
          <Text style={styles.bulletPoint}>• For shipments exceeding 5kg volumetric weight, billing will be done based on whichever is higher between dead weight and volumetric weight.</Text>
          <Text style={styles.paragraph}>
            Additionally, certain goods that require specialized handling, as defined under our internal operational guidelines, will be subject to an applicable special handling fee.
          </Text>

          <Text style={styles.sectionTitle}>III. CUSTOMER JOURNEY AFTER BOOKING OF SHIPMENT ON THE PLATFORMS</Text>
          <Text style={styles.paragraph}>
            Depending upon the pick-up location, you will be shown two options at the time of booking Shipments:
          </Text>
          <Text style={styles.bulletPoint}>• Ship Reward-Pickup: We come and collect the Shipments from Your doorstep (i.e. from the location provided by You)</Text>
          <Text style={styles.bulletPoint}>• Self-Ship: You are required to drop off the Shipments to Our nearest hub</Text>
          <Text style={styles.paragraph}>
            Once Your Shipment reaches Our hub, it is scanned, weighed and sorted as per the destination location and service selected. In case, there is any weight discrepancy in the weight mentioned and the weight recorded, it is put on hold and an email notification is sent to You for approval. Once approved it is connected to its destination.
          </Text>
          <Text style={styles.paragraph}>
            In case of international shipments, upon Shipments reaching the destination country after clearing the customs in India, the Shipments are custom cleared in the destination country and the Shipments are received at our local office from where it is forwarded to the last mile shipping carrier.
          </Text>
          <Text style={styles.subSectionTitle}>Our Shipping Vendors by Region:</Text>
          <Text style={styles.bulletPoint}>• USA: UPS, USPS and Fedex</Text>
          <Text style={styles.bulletPoint}>• Europe: DPD or postal networks</Text>
          <Text style={styles.bulletPoint}>• Canada: Canada Post and UPS</Text>
          <Text style={styles.paragraph}>
            Note: Our Shipping Vendors may change from time to time.
          </Text>

          <Text style={styles.subSectionTitle}>Delivery Attempts & RTOs:</Text>
          <Text style={styles.paragraph}>
            All Shipments are attempted to be delivered at least once, in many cases deliveries are attempted twice depending upon the last mile Shipping Vendor's policy. In case no one is available to receive the packages, the Shipments may be:
          </Text>
          <Text style={styles.bulletPoint}>• Dropped with the neighbour</Text>
          <Text style={styles.bulletPoint}>• Dropped to the local post office for pickup by the Customer</Text>
          <Text style={styles.bulletPoint}>• Dropped in a secure location outside the house or mailbox of the Customer</Text>

          <Text style={styles.subSectionTitle}>RTO under Ship Reward Direct Service:</Text>
          <Text style={styles.paragraph}>
            If any Shipment is undeliverable, the shipment will be forwarded back to Our or Our partner's local office in the destination country. The RTO charges will be billed to Your account and the package will be destroyed in most cases, except USA and Europe. Re-forwarding option is available for USA, Europe and the charges for the same will be extra.
          </Text>

          <Text style={styles.subSectionTitle}>Reasons for Shipment being Undeliverable:</Text>
          <Text style={styles.bulletPoint}>• Incorrect address mentioned at the time of booking and/or on the Shipment</Text>
          <Text style={styles.bulletPoint}>• Missing/incomplete information like apt number, street name etc.</Text>
          <Text style={styles.bulletPoint}>• Customer refused to accept the Shipment at the time of delivery</Text>
          <Text style={styles.bulletPoint}>• Customer refused to pay the taxes and/or duties</Text>

          <Text style={styles.sectionTitle}>IV. SHIP REWARD'S REFUND AND LIABILITY POLICY</Text>
          
          <Text style={styles.subSectionTitle}>Claims Maintainable:</Text>
          <Text style={styles.paragraph}>
            Our goal is to fulfil all Your Shipments securely however if anything goes wrong, we've got you covered! You may be entitled to file a claim and get compensation in the following circumstances:
          </Text>

          <Text style={styles.subSectionTitle}>Case 1: No first scan by the last mile carrier in the destination country</Text>
          <Text style={styles.bulletPoint}>• For 0-100g shipments: 30% of invoice value plus shipping charges, maximum Rs.1,000/- (Indian Rupees One Thousand Only) inclusive of shipping charges</Text>
          <Text style={styles.bulletPoint}>• For shipments above 100g: 30% of invoice plus shipping charges, maximum Rs.4,000/- (Indian Rupees Four Thousand Only) inclusive of shipping charges</Text>

          <Text style={styles.subSectionTitle}>Case 2: No delivery scan by the last mile Shipping Vendor or Shipment Lost in transit</Text>
          <Text style={styles.paragraph}>
            In case your customer claims for non-delivery and a refund has been made from your side to the customer, You may claim for a refund. Claim will be processed as per Claim Policy upon presentation of buyer-seller chat along with proof of refund.
          </Text>

          <Text style={styles.subSectionTitle}>Case 3: Package lost before inwarding in Delhi Hub</Text>
          <Text style={styles.paragraph}>
            If pickup is done by Ship Reward's team, refund will be as per policy. In case of 3PL (third party logistics) only the shipping charges will be refunded.
          </Text>

          <Text style={styles.subSectionTitle}>No Claims Maintainable:</Text>
          <Text style={styles.paragraph}>
            Ship Reward shall not be liable to entertain claims in the following circumstances:
          </Text>
          <Text style={styles.bulletPoint}>• Non-delivery due to wrong name/address or any wrong information</Text>
          <Text style={styles.bulletPoint}>• Shipment detained by customs or similar authority</Text>
          <Text style={styles.bulletPoint}>• Delivery attempt made but delivery not completed</Text>
          <Text style={styles.bulletPoint}>• Damage/leaking/tampering/pilferage due to poor packaging</Text>
          <Text style={styles.bulletPoint}>• Shipping Vendor does not provide for refund in the given circumstance</Text>
          <Text style={styles.bulletPoint}>• Shipping Vendor claims the Shipment is delivered</Text>

          <Text style={styles.subSectionTitle}>Process and Terms To Make Claim:</Text>
          <Text style={styles.bulletPoint}>1. Send your claim to support@shipreward.in with all supporting documents</Text>
          <Text style={styles.bulletPoint}>2. Ship Reward's support team will investigate and contact local office/Shipping Vendor</Text>
          <Text style={styles.bulletPoint}>3. Upon completion of investigation, Ship Reward will communicate the result</Text>
          <Text style={styles.bulletPoint}>4. Ship Reward endeavours to close each claim within 15 days</Text>
          <Text style={styles.bulletPoint}>5. For Ship Reward Direct services, refund entitlement after 30 days of pickup if not delivered</Text>
          <Text style={styles.bulletPoint}>6. Claims must be made within 60 days from the date of inward scan</Text>

          <Text style={styles.subSectionTitle}>Wallet Balance Refund:</Text>
          <Text style={styles.paragraph}>
            If any Non-GST registered customer does not perform any transaction for a period of 365 consecutive days, the wallet balance shall be refunded.
          </Text>

          <Text style={styles.sectionTitle}>V. HANDLING CHARGES, REMOTE AREA CHARGES, REFORWARDING CHARGES</Text>
          
          <Text style={styles.subSectionTitle}>Maximum Shipment Weight Limits:</Text>
          <Text style={styles.bulletPoint}>• USA: 22 KGs (volume or dead weight whichever is higher)</Text>
          <Text style={styles.bulletPoint}>• UK: 30 KGs (volume or dead weight whichever is higher)</Text>
          <Text style={styles.bulletPoint}>• Europe: 30 KGs (volume or dead weight whichever is higher)</Text>
          <Text style={styles.bulletPoint}>• Australia/NZ: 20 KGs (volume or dead weight whichever is higher)</Text>
          <Text style={styles.bulletPoint}>• Canada: 20 KGs (volume or dead weight whichever is higher)</Text>
          <Text style={styles.paragraph}>
            In case of package weight higher than above slabs, additional handling charge of Rs 4000/- plus GST applies, up to a maximum of additional 10 KGs.
          </Text>

          <Text style={styles.subSectionTitle}>Reforwarding Charges:</Text>
          <Text style={styles.bulletPoint}>• USA: $15 for up to 500 grams, $25 for 500g to 5 KG</Text>
          <Text style={styles.bulletPoint}>• Europe: €20 for up to 500 grams, €30 for 500g to 5 KG</Text>
          <Text style={styles.bulletPoint}>• Canada: CAD 20 for up to 500 grams, CAD 30 for 500g to 5 KG</Text>

          <Text style={styles.sectionTitle}>ANNEXURE A - PROHIBITED ITEMS</Text>
          <Text style={styles.paragraph}>
            The below-mentioned items are restricted and might not be accepted:
          </Text>
          <View style={styles.prohibitedList}>
            <Text style={styles.bulletPoint}>1. Alcohol, tobacco, drugs, contraband and poisonous goods</Text>
            <Text style={styles.bulletPoint}>2. Activated Sim Cards</Text>
            <Text style={styles.bulletPoint}>3. Air guns, replica and imitation firearms and arms and ammunitions</Text>
            <Text style={styles.bulletPoint}>4. Asbestos</Text>
            <Text style={styles.bulletPoint}>5. Corrosive items (acids, chemicals), radioactive material</Text>
            <Text style={styles.bulletPoint}>6. Biological Substance, Category B</Text>
            <Text style={styles.bulletPoint}>7. Corpses or human ashes</Text>
            <Text style={styles.bulletPoint}>8. Fruits and vegetables</Text>
            <Text style={styles.bulletPoint}>9. Fire extinguishers</Text>
            <Text style={styles.bulletPoint}>10. Pornography material</Text>
            <Text style={styles.bulletPoint}>11. Dry Ice</Text>
            <Text style={styles.bulletPoint}>12. Edible Oils, De-oiled groundnut cakes, Fodder and Rice bran</Text>
            <Text style={styles.bulletPoint}>13. Lottery tickets and Gambling devices</Text>
            <Text style={styles.bulletPoint}>14. Food items that require refrigeration</Text>
            <Text style={styles.bulletPoint}>15. Dangerous goods and Hazardous material</Text>
            <Text style={styles.bulletPoint}>16. Radioactive stuff</Text>
            <Text style={styles.bulletPoint}>17. Antiques</Text>
            <Text style={styles.bulletPoint}>18. Designer clothing</Text>
            <Text style={styles.bulletPoint}>19. Expensive jewellery</Text>
            <Text style={styles.bulletPoint}>20. Bullion (of any precious metal)</Text>
            <Text style={styles.bulletPoint}>21. Bacteria or virus samples</Text>
            <Text style={styles.bulletPoint}>22. Harmful chemicals</Text>
            <Text style={styles.bulletPoint}>23. Currency instruments</Text>
            <Text style={styles.bulletPoint}>24. Cigarettes</Text>
            <Text style={styles.bulletPoint}>25. Electronic Cigarettes</Text>
            <Text style={styles.bulletPoint}>26. Lithium Batteries</Text>
            <Text style={styles.bulletPoint}>27. Samsung Galaxy Note 7</Text>
            <Text style={styles.bulletPoint}>28. Magnets</Text>
            <Text style={styles.bulletPoint}>29. Speakers</Text>
            <Text style={styles.bulletPoint}>30. DNS</Text>
            <Text style={styles.bulletPoint}>31. Skin Sample</Text>
            <Text style={styles.bulletPoint}>32. Blood Sample</Text>
            <Text style={styles.bulletPoint}>33. Cosmetic</Text>
            <Text style={styles.bulletPoint}>34. Soaps</Text>
            <Text style={styles.bulletPoint}>35. Perfume</Text>
            <Text style={styles.bulletPoint}>36. Ignite substance or combust</Text>
            <Text style={styles.bulletPoint}>37. Medicine more than 3 Month Quantity</Text>
            <Text style={styles.bulletPoint}>38. Homeopathic Medicines</Text>
            <Text style={styles.bulletPoint}>39. Ayurvedic Medicines</Text>
            <Text style={styles.bulletPoint}>40. Red Chilli</Text>
            <Text style={styles.bulletPoint}>41. Seeds</Text>
            <Text style={styles.bulletPoint}>42. Plant Cells</Text>
            <Text style={styles.bulletPoint}>43. Govt Restricted Commodity (PPE Kit, N95 mask)</Text>
            <Text style={styles.bulletPoint}>44. More than 1 Battery Or Electric IEC mobile components</Text>
            <Text style={styles.bulletPoint}>45. Desktop PC</Text>
            <Text style={styles.bulletPoint}>46. Antiques</Text>
            <Text style={styles.bulletPoint}>47. Credit Cards</Text>
            <Text style={styles.bulletPoint}>48. Original Passport</Text>
            <Text style={styles.bulletPoint}>49. Animals, raw skins/furs, live stocks and its Articles</Text>
            <Text style={styles.bulletPoint}>50. Drones</Text>
            <Text style={styles.bulletPoint}>51. LED / LCD</Text>
            <Text style={styles.bulletPoint}>52. Hollow Musical Instruments (Tabla, Harmonium)</Text>
            <Text style={styles.bulletPoint}>53. Hoverboard</Text>
            <Text style={styles.bulletPoint}>54. Precious / Semi-Precious Jewellery</Text>
            <Text style={styles.bulletPoint}>55. Knives</Text>
            <Text style={styles.bulletPoint}>56. Needle</Text>
          </View>

          <Text style={styles.sectionTitle}>GOVERNING LAW AND JURISDICTION</Text>
          <Text style={styles.paragraph}>
            The Agreement shall be governed by the laws of India. You hereby agree that if any dispute(s) or difference(s) arise between You and Ship Reward, both parties shall attempt, for a period of 30 days from the receipt of a written notice from the other Party, to settle such dispute(s) by mutual discussions.
          </Text>
          <Text style={styles.paragraph}>
            If the said dispute(s) cannot be settled by mutual discussions within the 30-day period, such disputes shall be referred to arbitration by a sole arbitrator for final resolution in accordance with the provisions of the Arbitration and Conciliation Act, 1996. The arbitration proceedings shall be held in English language with the seat, venue and legal place of the arbitration being New Delhi.
          </Text>

          <Text style={styles.sectionTitle}>CUSTOMER SUPPORT</Text>
          <Text style={styles.paragraph}>
            If You have any questions, issues, complaint, or seek any clarity in relations to the Agreement and/or Services/Products, please feel free to contact us at:
          </Text>
          <Text style={styles.contactInfo}>Email: support@shipreward.in</Text>

          <Text style={styles.footer}>
            This Agreement is an electronic record in terms of Information Technology Act, 2000 and generated by a computer system, and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3(1)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021.
          </Text>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  content: {
    flex: 1,
    padding: isMobile ? 16 : 24,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: isMobile ? 20 : 40,
    maxWidth: 900,
    alignSelf: 'center',
    width: '100%',
  },
  mainTitle: {
    fontSize: isMobile ? 24 : 32,
    fontWeight: '700',
    color: COLORS.textDark,
    textAlign: 'center',
    marginBottom: 8,
  },
  version: {
    fontSize: 14,
    color: COLORS.gray,
    textAlign: 'center',
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.textDark,
    marginTop: 28,
    marginBottom: 12,
  },
  subSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textDark,
    marginTop: 20,
    marginBottom: 10,
  },
  paragraph: {
    fontSize: 15,
    color: COLORS.darkGray,
    lineHeight: 26,
    marginBottom: 16,
  },
  bulletPoint: {
    fontSize: 15,
    color: COLORS.darkGray,
    lineHeight: 28,
    paddingLeft: 8,
  },
  formula: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.primary,
    textAlign: 'center',
    backgroundColor: COLORS.lightGray,
    padding: 16,
    borderRadius: 8,
    marginVertical: 12,
  },
  prohibitedList: {
    marginTop: 8,
  },
  contactInfo: {
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: '600',
    marginTop: 8,
  },
  footer: {
    fontSize: 13,
    color: COLORS.gray,
    fontStyle: 'italic',
    marginTop: 32,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    lineHeight: 22,
  },
});
